# Generated by Django 4.2.7 on 2023-12-11 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MintBuy_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(null=True, upload_to='aboutimage/')),
            ],
        ),
    ]
