# Generated by Django 4.2.7 on 2023-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MintBuy_Accounts', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('hotline', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('support_mail', models.EmailField(max_length=30)),
            ],
        ),
    ]
