# Generated by Django 4.2.4 on 2023-09-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MintBuyApp', '0003_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
