# Generated by Django 4.2.4 on 2023-09-14 14:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MintBuyApp', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=False, populate_from='title', unique=True),
        ),
    ]
